# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(576, 620)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 581, 578))
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.field_text = QtWidgets.QTextEdit(self.widget)
        self.field_text.setObjectName("field_text")
        self.horizontalLayout_3.addWidget(self.field_text)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.list_notes = QtWidgets.QListWidget(self.widget)
        self.list_notes.setObjectName("list_notes")
        self.verticalLayout.addWidget(self.list_notes)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.button_note_create = QtWidgets.QPushButton(self.widget)
        self.button_note_create.setObjectName("button_note_create")
        self.horizontalLayout_2.addWidget(self.button_note_create)
        self.button_note_del = QtWidgets.QPushButton(self.widget)
        self.button_note_del.setObjectName("button_note_del")
        self.horizontalLayout_2.addWidget(self.button_note_del)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.button_note_save = QtWidgets.QPushButton(self.widget)
        self.button_note_save.setObjectName("button_note_save")
        self.verticalLayout.addWidget(self.button_note_save)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.list_tags = QtWidgets.QListWidget(self.widget)
        self.list_tags.setObjectName("list_tags")
        self.verticalLayout.addWidget(self.list_tags)
        self.field_tag = QtWidgets.QLineEdit(self.widget)
        self.field_tag.setObjectName("field_tag")
        self.verticalLayout.addWidget(self.field_tag)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.button_tag_add = QtWidgets.QPushButton(self.widget)
        self.button_tag_add.setObjectName("button_tag_add")
        self.horizontalLayout.addWidget(self.button_tag_add)
        self.button_tag_del = QtWidgets.QPushButton(self.widget)
        self.button_tag_del.setObjectName("button_tag_del")
        self.horizontalLayout.addWidget(self.button_tag_del)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.button_tag_search = QtWidgets.QPushButton(self.widget)
        self.button_tag_search.setObjectName("button_tag_search")
        self.verticalLayout.addWidget(self.button_tag_search)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 576, 19))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Список заміток"))
        self.button_note_create.setText(_translate("MainWindow", "Створити замітку"))
        self.button_note_del.setText(_translate("MainWindow", "Видалити замітку"))
        self.button_note_save.setText(_translate("MainWindow", "Зберегти замітку"))
        self.label.setText(_translate("MainWindow", "Список тегів"))
        self.field_tag.setText(_translate("MainWindow", "Введіть тег..."))
        self.button_tag_add.setText(_translate("MainWindow", "Додати до замітки"))
        self.button_tag_del.setText(_translate("MainWindow", "Відкріпити від замітки"))
        self.button_tag_search.setText(_translate("MainWindow", "Шукати замітки по тегу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
